-- =====================================================================
-- Mautus: schema completo
-- Execute este arquivo no SQL Editor do Supabase (uma única vez).
-- =====================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------
-- Tabelas
-- ---------------------------------------------------------------------

create table if not exists etapas (
  id uuid primary key default gen_random_uuid(),
  nome text not null unique,
  -- Nome normalizado pela aplicacao (NFC, minusculas em pt-BR): e ele que
  -- garante que "Corte" e "corte" nao sejam duas etapas.
  nome_chave text,
  ativa boolean not null default true
);

create table if not exists apontamentos (
  id uuid primary key default gen_random_uuid(),
  -- Contador sequencial por ordem de criacao: e o "#" da tabela do painel.
  numero bigint generated by default as identity,
  etapa_id uuid not null references etapas(id),
  numero_os text not null,
  tipo text not null check (tipo in ('OPERACAO','PAUSA')),
  inicio timestamptz not null,
  fim timestamptz not null,
  duracao_segundos int not null,
  justificativa text
);

-- Apontamento em curso de cada etapa. Uma linha por etapa, removida ao
-- finalizar. Fonte de verdade do tempo decorrido: o cronometro e sempre
-- recalculado por diferenca de timestamps a partir de segmento_inicio,
-- de modo que o tempo corre na nuvem mesmo com o navegador fechado.
create table if not exists sessoes (
  etapa_id uuid primary key references etapas(id),
  numero_os text not null,
  status text not null check (status in ('EM_ANDAMENTO','PAUSADO')),
  segmento_inicio timestamptz not null,
  motivo text
);

-- Usuarios do painel. A tela de apontamento nao tem login (regra 7); estes
-- perfis valem so para o painel de gestao: GESTOR faz tudo, VENDEDOR so
-- consulta OS, para saber onde esta o material do cliente.
create table if not exists usuarios (
  id             uuid primary key default gen_random_uuid(),
  nome           text not null,
  -- Mesma normalizacao das etapas: "Joao" e "JOAO" sao a mesma pessoa.
  nome_chave     text,
  tipo           text not null check (tipo in ('GESTOR','VENDEDOR')),
  ativo          boolean not null default true,
  senha_hash     text not null,
  primeiro_login boolean not null default true,
  -- Muda a cada troca de senha, reset e inativacao; o cookie guarda o valor
  -- da hora do login, e quando nao bate mais a sessao foi revogada.
  versao_sessao  integer not null default 0
);

-- Configuracao do proprio sistema: hoje so a chave que assina os cookies de
-- sessao. Fica no banco para o sistema subir sem configuracao nenhuma e para
-- ninguem cair ao reiniciar o servidor.
create table if not exists configuracao (
  chave text primary key,
  valor text not null
);

-- ---------------------------------------------------------------------
-- Migracao de bancos criados por versoes anteriores deste arquivo
-- ---------------------------------------------------------------------

-- Cada passo confere antes de agir: em banco novo, nada acontece. Os indices
-- vem depois, porque um banco antigo ainda nao tem as colunas que eles usam.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
     where table_name = 'apontamentos' and column_name = 'numero'
  ) then
    alter table apontamentos add column numero bigint generated by default as identity;
    with ordenados as (
      select id, row_number() over (order by inicio, id) as seq from apontamentos
    )
    update apontamentos a set numero = o.seq from ordenados o where o.id = a.id;
  end if;
end $$;

alter table etapas   add column if not exists nome_chave text;
alter table usuarios add column if not exists nome_chave text;
alter table usuarios add column if not exists versao_sessao integer not null default 0;

-- Preenchimento aproximado das linhas antigas. Daqui em diante a aplicacao
-- grava a chave com a regra exata de src/lib/nomes.ts.
update etapas   set nome_chave = lower(normalize(nome, NFC)) where nome_chave is null;
update usuarios set nome_chave = lower(normalize(nome, NFC)) where nome_chave is null;

-- ---------------------------------------------------------------------
-- Indices
-- ---------------------------------------------------------------------

create index if not exists apontamentos_numero_os_idx on apontamentos (numero_os);
create index if not exists apontamentos_inicio_idx on apontamentos (inicio);
-- Contagem por etapa, filtros e o aviso de OS repetida na mesma etapa.
create index if not exists apontamentos_etapa_idx on apontamentos (etapa_id, numero_os);

-- O "#" passa a ser unico: dois registros com o mesmo numero seriam
-- impossiveis de distinguir na tabela.
drop index if exists apontamentos_numero_idx;
create unique index if not exists apontamentos_numero_unico on apontamentos (numero);

drop index if exists usuarios_nome_idx;
create unique index if not exists etapas_nome_chave_unico on etapas (nome_chave);
create unique index if not exists usuarios_nome_chave_unico on usuarios (nome_chave);

-- ---------------------------------------------------------------------
-- Revogacao de sessoes
-- ---------------------------------------------------------------------

-- A API REST nao sabe escrever `versao_sessao = versao_sessao + 1`, e ler
-- para depois gravar deixaria duas revogacoes simultaneas valerem por uma.
-- O gatilho faz o incremento dentro do proprio update: trocar a senha ou
-- mudar o `ativo` derruba toda sessao aberta daquele usuario.
create or replace function usuarios_revogar_sessoes() returns trigger
language plpgsql
as $fn$
begin
  if new.senha_hash is distinct from old.senha_hash
     or new.ativo is distinct from old.ativo then
    new.versao_sessao := old.versao_sessao + 1;
  end if;
  return new;
end
$fn$;

drop trigger if exists usuarios_revogar_sessoes on usuarios;
create trigger usuarios_revogar_sessoes
  before update on usuarios
  for each row execute function usuarios_revogar_sessoes();

-- ---------------------------------------------------------------------
-- Avanco de segmento: as duas escritas numa transacao so
-- ---------------------------------------------------------------------

-- Fechar o segmento aberto e abrir o seguinte sao duas escritas que precisam
-- valer juntas. Em duas chamadas separadas, uma queda de rede no meio deixaria
-- o apontamento gravado e a sessao no estado antigo, e dois cliques no mesmo
-- botao gravariam o mesmo segmento duas vezes. Aqui a linha da sessao e travada
-- (`for update`): o segundo clique espera, entra, encontra o status ja mudado e
-- devolve false sem escrever nada.
--
-- `p_novo_status` nulo significa finalizar: grava o ultimo segmento e libera a
-- etapa. O inicio do proximo segmento e sempre `p_fim`, de modo que nao existe
-- caminho no codigo capaz de abrir uma lacuna entre segmentos (regra 2).
create or replace function avancar_segmento(
  p_etapa_id        uuid,
  p_status_esperado text,
  p_fim             timestamptz,
  p_novo_status     text,
  p_novo_motivo     text
) returns boolean
language plpgsql
security definer
set search_path = public
as $fn$
declare
  s sessoes;
begin
  select * into s from sessoes where etapa_id = p_etapa_id for update;

  -- Sessao inexistente ou ja alterada por outra aba: nada a fazer.
  if not found or s.status <> p_status_esperado then
    return false;
  end if;

  insert into apontamentos
    (etapa_id, numero_os, tipo, inicio, fim, duracao_segundos, justificativa)
  values (
    s.etapa_id,
    s.numero_os,
    case when s.status = 'EM_ANDAMENTO' then 'OPERACAO' else 'PAUSA' end,
    s.segmento_inicio,
    p_fim,
    greatest(0, extract(epoch from (p_fim - s.segmento_inicio))::int),
    -- Justificativa so existe em segmento de pausa.
    case when s.status = 'PAUSADO' then s.motivo else null end
  );

  if p_novo_status is null then
    delete from sessoes where etapa_id = p_etapa_id;
  else
    update sessoes
       set status = p_novo_status,
           segmento_inicio = p_fim,
           motivo = p_novo_motivo
     where etapa_id = p_etapa_id;
  end if;

  return true;
end
$fn$;

-- ---------------------------------------------------------------------
-- Acesso: somente pelo servidor
-- ---------------------------------------------------------------------

-- A tela de apontamento nao tem login (regra 7), e o login do painel e da
-- propria aplicacao, nao do Supabase. Por isso mesmo o banco nao pode ficar
-- aberto ao papel anonimo: a chave publicavel de um projeto Supabase viaja no
-- navegador de qualquer visitante, e com RLS liberada ela daria acesso de
-- leitura, escrita e exclusao direto pela API REST.
--
-- Todo o acesso passa pelas Server Actions, no servidor, com a chave
-- `service_role`, que nunca chega ao navegador e ignora RLS por natureza.
-- Entao: RLS ligada e nenhuma politica. Sem politica, anon e authenticated nao
-- leem nem gravam nada; o servidor continua com acesso total.
alter table etapas       enable row level security;
alter table apontamentos enable row level security;
alter table sessoes      enable row level security;
alter table usuarios     enable row level security;
alter table configuracao enable row level security;

-- Politicas permissivas de versoes anteriores deste arquivo.
drop policy if exists etapas_anon       on etapas;
drop policy if exists apontamentos_anon on apontamentos;
drop policy if exists sessoes_anon      on sessoes;

-- RLS sozinha nao basta: sem o revoke, as tabelas continuariam visiveis para o
-- papel anonimo caso alguem crie uma politica por engano mais tarde.
revoke all on etapas, apontamentos, sessoes, usuarios, configuracao
  from anon, authenticated;
revoke execute on function avancar_segmento(uuid, text, timestamptz, text, text)
  from public, anon, authenticated;
revoke execute on function usuarios_revogar_sessoes()
  from public, anon, authenticated;

-- ---------------------------------------------------------------------
-- Cadastro inicial de etapas: as máquinas e os setores da gráfica
-- ---------------------------------------------------------------------

-- Espelho de src/lib/etapas-iniciais.ts, que e a fonte unica. Ao mudar a
-- lista la, gere este bloco de novo em vez de editar a mao.
insert into etapas (nome, nome_chave) values
  ('GOSS', 'goss'),
  ('Komori', 'komori'),
  ('SM', 'sm'),
  ('KBA', 'kba'),
  ('Dobradeira MBO', 'dobradeira mbo'),
  ('Dobradeira AR', 'dobradeira ar'),
  ('Laminação', 'laminação'),
  ('Corte/Vinco Automático', 'corte/vinco automático'),
  ('Corte/Vinco Manual', 'corte/vinco manual'),
  ('Alceadeira 10 gavetas', 'alceadeira 10 gavetas'),
  ('Alceadeira 5 gavetas', 'alceadeira 5 gavetas'),
  ('Alceadeira Torre', 'alceadeira torre'),
  ('Guilhotina 115 Tiger', 'guilhotina 115 tiger'),
  ('Guilhotina 115 [revisar]', 'guilhotina 115 [revisar]'),
  ('Guilhotina [revisar]', 'guilhotina [revisar]'),
  ('Verniz Localizado', 'verniz localizado'),
  ('Grampeador Miruna', 'grampeador miruna'),
  ('Desfoleadeira', 'desfoleadeira'),
  ('Máquina de aplicar vareta', 'máquina de aplicar vareta'),
  ('Cartucheira', 'cartucheira'),
  ('Máquina de copo 01', 'máquina de copo 01'),
  ('Máquina de copo 02', 'máquina de copo 02'),
  ('Máquina de copo 03', 'máquina de copo 03'),
  ('Máquina de copo 04', 'máquina de copo 04'),
  ('Máquina de balde 5L', 'máquina de balde 5l'),
  ('Coladeira PUR', 'coladeira pur'),
  ('Shirincadeira Automática', 'shirincadeira automática'),
  ('Shirincadeira manual', 'shirincadeira manual'),
  ('Expedição', 'expedição'),
  ('Ricoh', 'ricoh')
on conflict (nome) do nothing;
