-- =====================================================================
-- Sistema de Apontamento Gráfico — schema completo
-- Execute este arquivo no SQL Editor do Supabase (uma única vez).
-- =====================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------
-- Tabelas
-- ---------------------------------------------------------------------

create table if not exists etapas (
  id uuid primary key default gen_random_uuid(),
  nome text not null unique,
  ativa boolean not null default true
);

create table if not exists apontamentos (
  id uuid primary key default gen_random_uuid(),
  -- Contador sequencial por ordem de criacao: e o "#" da tabela do painel.
  numero bigint generated by default as identity,
  etapa_id uuid not null references etapas(id),
  numero_os text not null,
  tipo text not null check (tipo in ('OPERACAO','PAUSA')),
  inicio timestamptz not null,
  fim timestamptz not null,
  duracao_segundos int not null,
  justificativa text
);

-- Apontamento em curso de cada etapa. Uma linha por etapa, removida ao
-- finalizar. Fonte de verdade do tempo decorrido: o cronômetro é sempre
-- recalculado por diferença de timestamps a partir de segmento_inicio,
-- de modo que o tempo corre na nuvem mesmo com o navegador fechado.
create table if not exists sessoes (
  etapa_id uuid primary key references etapas(id),
  numero_os text not null,
  status text not null check (status in ('EM_ANDAMENTO','PAUSADO')),
  segmento_inicio timestamptz not null,
  motivo text
);

create index if not exists apontamentos_numero_os_idx on apontamentos (numero_os);
create index if not exists apontamentos_inicio_idx on apontamentos (inicio);
create index if not exists apontamentos_numero_idx on apontamentos (numero);

-- Para bancos criados antes da coluna `numero`: adiciona e numera em ordem
-- cronologica. Em banco novo nao faz nada.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
     where table_name = 'apontamentos' and column_name = 'numero'
  ) then
    alter table apontamentos add column numero bigint generated by default as identity;
    with ordenados as (
      select id, row_number() over (order by inicio, id) as seq from apontamentos
    )
    update apontamentos a set numero = o.seq from ordenados o where o.id = a.id;
  end if;
end $$;

-- Usuarios do painel. A tela de apontamento nao tem login (regra 1); estes
-- perfis valem so para o painel de gestao: GESTOR ve tudo, VENDEDOR ve apenas
-- o dashboard, para saber onde esta o material do cliente.
--
-- `citext` nao esta ligado por padrao, entao a unicidade sem diferenciar
-- maiusculas sai de um indice sobre lower(nome): cadastrar "Joao" e depois
-- "joao" seria criar dois acessos para a mesma pessoa.
create table if not exists usuarios (
  id             uuid primary key default gen_random_uuid(),
  nome           text not null,
  tipo           text not null check (tipo in ('GESTOR','VENDEDOR')),
  ativo          boolean not null default true,
  senha_hash     text not null,
  primeiro_login boolean not null default true
);

create unique index if not exists usuarios_nome_idx on usuarios (lower(nome));

-- Configuracao do proprio sistema: hoje so a chave que assina os cookies de
-- sessao. Fica no banco para o sistema subir sem configuracao nenhuma e para
-- ninguem cair ao reiniciar o servidor.
create table if not exists configuracao (
  chave text primary key,
  valor text not null
);

-- ---------------------------------------------------------------------
-- Avanco de segmento: as duas escritas numa transacao so
-- ---------------------------------------------------------------------

-- Fechar o segmento aberto e abrir o seguinte sao duas escritas que precisam
-- valer juntas. Em duas chamadas separadas, uma queda de rede no meio deixaria
-- o apontamento gravado e a sessao no estado antigo -- e dois cliques no mesmo
-- botao gravariam o mesmo segmento duas vezes. Aqui a linha da sessao e travada
-- (`for update`): o segundo clique espera, entra, encontra o status ja mudado e
-- devolve false sem escrever nada.
--
-- `p_novo_status` nulo significa finalizar: grava o ultimo segmento e libera a
-- etapa. O inicio do proximo segmento e sempre `p_fim`, de modo que nao existe
-- caminho no codigo capaz de abrir uma lacuna entre segmentos (regra 2).
create or replace function avancar_segmento(
  p_etapa_id        uuid,
  p_status_esperado text,
  p_fim             timestamptz,
  p_novo_status     text,
  p_novo_motivo     text
) returns boolean
language plpgsql
security definer
set search_path = public
as $fn$
declare
  s sessoes;
begin
  select * into s from sessoes where etapa_id = p_etapa_id for update;

  -- Sessao inexistente ou ja alterada por outra aba: nada a fazer.
  if not found or s.status <> p_status_esperado then
    return false;
  end if;

  insert into apontamentos
    (etapa_id, numero_os, tipo, inicio, fim, duracao_segundos, justificativa)
  values (
    s.etapa_id,
    s.numero_os,
    case when s.status = 'EM_ANDAMENTO' then 'OPERACAO' else 'PAUSA' end,
    s.segmento_inicio,
    p_fim,
    greatest(0, extract(epoch from (p_fim - s.segmento_inicio))::int),
    -- Justificativa so existe em segmento de pausa.
    case when s.status = 'PAUSADO' then s.motivo else null end
  );

  if p_novo_status is null then
    delete from sessoes where etapa_id = p_etapa_id;
  else
    update sessoes
       set status = p_novo_status,
           segmento_inicio = p_fim,
           motivo = p_novo_motivo
     where etapa_id = p_etapa_id;
  end if;

  return true;
end
$fn$;

-- ---------------------------------------------------------------------
-- Acesso: somente pelo servidor
-- ---------------------------------------------------------------------

-- O sistema nao tem login (regra 1), e por isso mesmo o banco nao pode ficar
-- aberto ao papel anonimo: a chave publicavel de um projeto Supabase viaja no
-- navegador de qualquer visitante, e com RLS liberada ela daria acesso de
-- leitura, escrita e exclusao direto pela API REST.
--
-- Todo o acesso passa pelas Server Actions, no servidor, com a chave
-- `service_role` -- que nunca chega ao navegador e ignora RLS por natureza.
-- Entao: RLS ligada e nenhuma politica. Sem politica, anon e authenticated nao
-- leem nem gravam nada; o servidor continua com acesso total.
alter table etapas       enable row level security;
alter table apontamentos enable row level security;
alter table sessoes      enable row level security;
alter table usuarios     enable row level security;
alter table configuracao enable row level security;

-- Politicas permissivas de versoes anteriores deste arquivo.
drop policy if exists etapas_anon       on etapas;
drop policy if exists apontamentos_anon on apontamentos;
drop policy if exists sessoes_anon      on sessoes;

-- RLS sozinha nao basta: sem o revoke, as tabelas continuariam visiveis para o
-- papel anonimo caso alguem crie uma politica por engano mais tarde.
revoke all on etapas, apontamentos, sessoes, usuarios, configuracao
  from anon, authenticated;
revoke execute on function avancar_segmento(uuid, text, timestamptz, text, text)
  from public, anon, authenticated;

-- ---------------------------------------------------------------------
-- Cadastro inicial de etapas: as máquinas e os setores da gráfica
-- ---------------------------------------------------------------------

insert into etapas (nome) values
  ('GOSS'),
  ('Komori'),
  ('SM'),
  ('KBA'),
  ('Dobradeira MBO'),
  ('Dobradeira AR'),
  ('Laminacao'),
  ('Corte/Vinco Automatico'),
  ('Corte/Vinco Manual'),
  ('Alceadeira 10 gavetas'),
  ('Alceadeira 5 gavetas'),
  ('Alceadeira Torre'),
  ('Guilhotina 115 Tiger'),
  ('Guilhotina 115 [revisar]'),
  ('Guilhotina [revisar]'),
  ('Verniz Localizado'),
  ('Grampeador Miruna'),
  ('Desfoleadeira'),
  ('Maquina de aplicar vareta'),
  ('Cartucheira'),
  ('Maquina de copo 01'),
  ('Maquina de copo 02'),
  ('Maquina de copo 03'),
  ('Maquina de copo 04'),
  ('Maquina de balde 5L'),
  ('Coladeira PUR'),
  ('Shirincadeira Autoamtica'),
  ('Shirincadeira manual'),
  ('Expedicao'),
  ('Ricoh')
on conflict (nome) do nothing;
